const fieldLabels = {
  LName: "Last Name",
  FName: "First Name",
  MiddleI: "Middle Initial",
  Preferred: "Preferred Name",
  Birthdate: "Date of Birth",
  SSN: "Social Security Number",
  Gender: "Gender",
  Position: "Married",
  WkPhone: "Work Phone",
  WirelessPhone: "Mobile Phone",
  HmPhone: "Home Phone",
  Email: "Email Address",
  PreferContactMethod: "Preferred Contact Method",
  PreferConfirmMethod: "Confirmation Contact Method",
  PreferRecallMethod: "Recall Contact Method",
  StudentStatus: "Student Status",
  referredFrom: "Referred From",
  Address: "Address",
  Address2: "Address (Line 2)",
  City: "City",
  State: "State",
  Zip: "ZIP Code",
  ins1Relat: "Relationship to Subscriber (Policy 1)",
  ins1SubscriberNameF: "Subscriber Name (Policy 1)",
  ins1SubscriberID: "Subscriber ID (Policy 1)",
  ins1CarrierName: "Insurance Company (Policy 1)",
  ins1CarrierPhone: "Insurance Phone (Policy 1)",
  ins1EmployerName: "Employer (Policy 1)",
  ins1GroupName: "Group Name (Policy 1)",
  ins1GroupNum: "Group Number (Policy 1)",
  ins2Relat: "Relationship to Subscriber (Policy 2)",
  ins2SubscriberNameF: "Subscriber Name (Policy 2)",
  ins2SubscriberID: "Subscriber ID (Policy 2)",
  ins2CarrierName: "Insurance Company (Policy 2)",
  ins2CarrierPhone: "Insurance Phone (Policy 2)",
  ins2EmployerName: "Employer (Policy 2)",
  ins2GroupName: "Group Name (Policy 2)",
  ins2GroupNum: "Group Number (Policy 2)",
  misc: "Other Authorized Party",
};

module.exports = fieldLabels;
